local ids = {
	ability = 1346,
	passives = 515,
	collars = 753,
	divineShield = 2693,
	shield = 2695,
	str = 2704,
	spd = 2707,
	int = 2710,
	dex = 2713,
	con = 2716,
	cha = 2719,
	lck = 3896,

}
local paths = {}
paths.mewbox = "./mewbox-data"
paths.assets = {
	unsorted = {
		ability = paths.mewbox .. "/DefineSprite_" .. ids.ability .. "_AbilityIcon",
		passive = paths.mewbox .. "/DefineSprite_" .. ids.passives .. "_PassiveIcon",
		collars = paths.mewbox .. "/DefineSprite_" .. ids.collars .. "_ClassCollar",
		divineShield = paths.mewbox .. "/DefineSprite_" .. ids.divineShield .. "_RawFontIcon_divineshield",
		shield = paths.mewbox .. "/DefineSprite_" .. ids.shield .. "_RawFontIcon_shield",
		str = paths.mewbox .. "/DefineSprite_" .. ids.str .. "_FontIcon_str",
		spd = paths.mewbox .. "/DefineSprite_" .. ids.spd .. "_FontIcon_spd",
		int = paths.mewbox .. "/DefineSprite_" .. ids.int .. "_FontIcon_int",
		dex = paths.mewbox .. "/DefineSprite_" .. ids.dex .. "_FontIcon_dex",
		con = paths.mewbox .. "/DefineSprite_" .. ids.con .. "_FontIcon_con",
		cha = paths.mewbox .. "/DefineSprite_" .. ids.cha .. "_FontIcon_cha",
		lck = paths.mewbox .. "/DefineSprite_" .. ids.lck .. "_FontIcon_lck",
		shells = "./static/shells",
		fonts = paths.mewbox .. "TODO",
	},
	final = {
		ability = paths.mewbox .. "/abilityIcons",
		passive = paths.mewbox .. "/passiveIcons",
		collars = paths.mewbox .. "/collarIcons",
		fontIcons = paths.mewbox .. "/fontIcons",
		shells = paths.mewbox .. "/shells",
		fonts = paths.mewbox .. "/fonts",
	},
	swf = {
		ability = "./mewgenics-data/swfs/ability_icons.swf",
		ui = "./mewgenics-data/swfs/ui.swf",
		fonts = "./mewgenics-data/swfs/fonts.swf",
	}
}
paths.data = {
	json = {
		folder = paths.mewbox .. "",
		passives = paths.mewbox .. "/passives.json",
		abilities = paths.mewbox .. "/abilities.json",
	},
	csv = {
		"./mewgenics-data/data/text/abilities.csv",
		"./mewgenics-data/data/text/additions2.csv",
		"./mewgenics-data/data/text/additions3.csv",
		"./mewgenics-data/data/text/additions.csv",
		"./mewgenics-data/data/text/cutscene_text.csv",
		"./mewgenics-data/data/text/enemy_abilities.csv",
		"./mewgenics-data/data/text/events.csv",
		"./mewgenics-data/data/text/furniture.csv",
		"./mewgenics-data/data/text/items.csv",
		"./mewgenics-data/data/text/keyword_tooltips.csv",
		"./mewgenics-data/data/text/misc.csv",
		"./mewgenics-data/data/text/mutations.csv",
		"./mewgenics-data/data/text/npc_dialog.csv",
		"./mewgenics-data/data/text/passives.csv",
		"./mewgenics-data/data/text/progression.csv",
		"./mewgenics-data/data/text/pronouns.csv",
		"./mewgenics-data/data/text/teamnames.csv",
		"./mewgenics-data/data/text/units.csv",
		"./mewgenics-data/data/text/weather.csv",
	},
	gon = {
		passives = {
			"./mewgenics-data/data/passives/butcher_passives.gon",
			"./mewgenics-data/data/passives/colorless_passives.gon",
			"./mewgenics-data/data/passives/disorders.gon",
			"./mewgenics-data/data/passives/druid_passives.gon",
			"./mewgenics-data/data/passives/fighter_passives.gon",
			"./mewgenics-data/data/passives/hunter_passives.gon",
			"./mewgenics-data/data/passives/jester_passives.gon",
			"./mewgenics-data/data/passives/mage_passives.gon",
			"./mewgenics-data/data/passives/medic_passives.gon",
			"./mewgenics-data/data/passives/monk_passives.gon",
			"./mewgenics-data/data/passives/necromancer_passives.gon",
			"./mewgenics-data/data/passives/psychic_passives.gon",
			"./mewgenics-data/data/passives/tank_passives.gon",
			"./mewgenics-data/data/passives/thief_passives.gon",
			"./mewgenics-data/data/passives/tinkerer_passives.gon",
			"./mewgenics-data/data/passives/util_passives.gon",
		},
		abilities = {
			"./mewgenics-data/data/abilities/abilities.gon",
			"./mewgenics-data/data/abilities/armor_abilities.gon",
			"./mewgenics-data/data/abilities/basic_attacks.gon",
			"./mewgenics-data/data/abilities/basic_movement.gon",
			"./mewgenics-data/data/abilities/butcher_abilities.gon",
			"./mewgenics-data/data/abilities/colorless_abilities.gon",
			"./mewgenics-data/data/abilities/consumable_item_abilities.gon",
			"./mewgenics-data/data/abilities/contextual_abilities.gon",
			"./mewgenics-data/data/abilities/disorder_abilities.gon",
			"./mewgenics-data/data/abilities/druid_abilities.gon",
			"./mewgenics-data/data/abilities/event_abilities.gon",
			"./mewgenics-data/data/abilities/fighter_abilities.gon",
			"./mewgenics-data/data/abilities/finalboss_abilities.gon",
			"./mewgenics-data/data/abilities/guillotina_abilities.gon",
			"./mewgenics-data/data/abilities/hunter_abilities.gon",
			"./mewgenics-data/data/abilities/item_abilities.gon",
			"./mewgenics-data/data/abilities/jester_abilities.gon",
			"./mewgenics-data/data/abilities/kaiju_abilities.gon",
			"./mewgenics-data/data/abilities/mage_abilities.gon",
			"./mewgenics-data/data/abilities/medic_abilities.gon",
			"./mewgenics-data/data/abilities/misc_abilities.gon",
			"./mewgenics-data/data/abilities/monk_abilities.gon",
			"./mewgenics-data/data/abilities/necromancer_abilities.gon",
			"./mewgenics-data/data/abilities/psychic_abilities.gon",
			"./mewgenics-data/data/abilities/rifthead_abilities.gon",
			"./mewgenics-data/data/abilities/special_enemy_abilities.gon",
			"./mewgenics-data/data/abilities/tank_abilities.gon",
			"./mewgenics-data/data/abilities/terminator_abilities.gon",
			"./mewgenics-data/data/abilities/test_abilities.gon",
			"./mewgenics-data/data/abilities/thief_abilities.gon",
			"./mewgenics-data/data/abilities/throbbing_king_abilities.gon",
			"./mewgenics-data/data/abilities/tinkerer_abilities.gon",
			"./mewgenics-data/data/abilities/util_abilities.gon",
		}
	}
}
return paths
